@extends('layout.layout')
@section('judul', 'Pengurus kelas')
@section('page-description', 'Tentukan siswa yang membantu menjaga ritme dan validasi kelas.')
@section('page-actions')<a href="{{ route('wali-kelas.pengurus-kelas.create') }}" class="btn btn-primary page-action"><i class="ph-bold ph-plus" aria-hidden="true"></i> Tambah pengurus</a>@endsection

@section('isi')
    <section class="workspace-page" aria-labelledby="wali-pengurus-title">
        <header class="workspace-intro"><div><p class="eyebrow">Ruang wali kelas</p><h2 id="wali-pengurus-title">Struktur pengurus kelas.</h2><p>Jaga peran ketua, wakil, dan sekretaris tetap jelas.</p></div><span class="workspace-index">02 / Kelas</span></header>
        <form action="" method="get" class="workspace-filters" id="form"><label class="search-field" for="keyword"><span class="sr-only">Cari pengurus</span><i class="ph-bold ph-magnifying-glass" aria-hidden="true"></i><input id="keyword" type="search" name="keyword" value="{{ old('keyword', request('keyword')) }}" placeholder="Cari nama atau NIS..."></label><select class="form-select filter" name="filter_jabatan"><option value="">Semua jabatan</option><option value="ketua_kelas" {{ request('filter_jabatan') === 'ketua_kelas' ? 'selected' : '' }}>Ketua kelas</option><option value="wakil_kelas" {{ request('filter_jabatan') === 'wakil_kelas' ? 'selected' : '' }}>Wakil kelas</option><option value="sekretaris" {{ request('filter_jabatan') === 'sekretaris' ? 'selected' : '' }}>Sekretaris</option></select><button type="submit" class="btn btn-secondary">Terapkan</button></form>
        <div class="table-scroll" tabindex="0" aria-label="Tabel pengurus kelas"><table class="table table-bordered"><thead><tr><th scope="col">No</th><th scope="col">Nama lengkap</th><th scope="col">NIS</th><th scope="col">Jabatan</th><th scope="col">Kelas</th><th scope="col">Aksi</th></tr></thead><tbody>@forelse ($pengurus as $item)<tr><td>{{ $loop->iteration }}</td><td><strong class="table-primary-text">{{ $item->nama_siswa }}</strong></td><td>{{ $item->nis }}</td><td><span class="role-label">{{ $item->status_jabatan }}</span></td><td>{{ $item->nama_kelas }}</td><td class="table-actions"><a class="icon-action icon-action--info" href="{{ route('wali-kelas.pengurus-kelas.detail-siswa', ['id' => $item->id_siswa]) }}" aria-label="Lihat {{ $item->nama_siswa }}" title="Lihat pengurus"><i class="ph-bold ph-arrow-up-right" aria-hidden="true"></i></a><a class="icon-action icon-action--edit" href="{{ route('wali-kelas.pengurus-kelas.edit', ['id' => $item->id_pengurus]) }}" aria-label="Edit {{ $item->nama_siswa }}" title="Edit pengurus"><i class="ph-bold ph-pencil-simple" aria-hidden="true"></i></a><button type="button" class="icon-action icon-action--danger" data-delete-url="{{ route('wali-kelas.pengurus-kelas.destroy') }}" data-delete-field="id_pengurus" data-delete-id="{{ $item->id_pengurus }}" aria-label="Hapus {{ $item->nama_siswa }}" title="Hapus pengurus"><i class="ph-bold ph-trash" aria-hidden="true"></i></button></td></tr>@empty<tr><td colspan="6"><div class="table-empty-state"><i class="ph-bold ph-users-three" aria-hidden="true"></i><strong>Belum ada pengurus</strong><span>Tambahkan siswa yang akan membantu kelas.</span></div></td></tr>@endforelse</tbody></table></div>{{ $pengurus->links() }}
    </section>
@endsection
