@extends('layout.layout')
@section('judul', 'Siswa kelas')
@section('page-description', 'Tinjau data siswa yang berada dalam tanggung jawab kelas Anda.')

@section('isi')
    <section class="workspace-page" aria-labelledby="wali-siswa-title">
        <header class="workspace-intro"><div><p class="eyebrow">Ruang wali kelas</p><h2 id="wali-siswa-title">Siswa dalam kelas Anda.</h2><p>Data ini menjadi dasar untuk tindak lanjut presensi dan administrasi harian.</p></div><span class="workspace-index">01 / Kelas</span></header>
        <form action="" method="get" class="workspace-filters" id="form"><label class="search-field" for="keyword"><span class="sr-only">Cari siswa</span><i class="ph-bold ph-magnifying-glass" aria-hidden="true"></i><input id="keyword" type="search" name="keyword" value="{{ old('keyword', request('keyword')) }}" placeholder="Cari nama atau NIS..."></label><select class="form-select filter" name="filter_jenkel"><option value="">Semua gender</option><option value="laki-laki" {{ request('filter_jenkel') === 'laki-laki' ? 'selected' : '' }}>Laki-laki</option><option value="perempuan" {{ request('filter_jenkel') === 'perempuan' ? 'selected' : '' }}>Perempuan</option></select><button type="submit" class="btn btn-secondary">Terapkan</button></form>
        <div class="table-scroll" tabindex="0" aria-label="Tabel siswa kelas"><table class="table table-bordered"><thead><tr><th scope="col">No</th><th scope="col">Profil</th><th scope="col">NIS</th><th scope="col">Nama lengkap</th><th scope="col">Gender</th><th scope="col">Kelas</th><th scope="col">Aksi</th></tr></thead><tbody>@forelse ($siswa as $item)<tr><td>{{ $loop->iteration }}</td><td>@include('layout.partials.entity-avatar', ['directory' => 'siswa', 'filename' => $item->foto_siswa, 'alt' => 'Foto '.$item->nama_siswa])</td><td>{{ $item->nis }}</td><td><strong class="table-primary-text">{{ $item->nama_siswa }}</strong></td><td>{{ $item->jenis_kelamin }}</td><td>{{ $item->tingkatan.' '.$item->nama_jurusan.' '.$item->nama_kelas }}</td><td class="table-actions"><a class="icon-action icon-action--info" href="{{ route('wali-kelas.siswa.detail', ['id' => $item->id_siswa]) }}" aria-label="Lihat {{ $item->nama_siswa }}" title="Lihat siswa"><i class="ph-bold ph-arrow-up-right" aria-hidden="true"></i></a><a class="icon-action icon-action--edit" href="{{ route('wali-kelas.siswa.edit', ['id' => $item->id_siswa]) }}" aria-label="Edit {{ $item->nama_siswa }}" title="Edit siswa"><i class="ph-bold ph-pencil-simple" aria-hidden="true"></i></a></td></tr>@empty<tr><td colspan="7"><div class="table-empty-state"><i class="ph-bold ph-users-three" aria-hidden="true"></i><strong>Belum ada siswa yang cocok</strong><span>Ubah filter untuk melihat data kelas.</span></div></td></tr>@endforelse</tbody></table></div>{{ $siswa->links() }}
    </section>
@endsection
