@extends('layout.layout')
@section('judul', 'Pengurus kelas')
@section('page-description', 'Lihat siswa yang bertugas membantu presensi dan koordinasi kelas.')

@section('isi')
    <section class="workspace-page" aria-labelledby="piket-pengurus-title">
        <header class="workspace-intro"><div><p class="eyebrow">Operasi piket</p><h2 id="piket-pengurus-title">Pengurus kelas yang bertugas.</h2><p>Gunakan filter untuk membuka detail pengurus tanpa mengubah data.</p></div><span class="workspace-index">01 / Piket</span></header>
        <form action="" method="get" class="workspace-filters" id="form"><label class="search-field" for="keyword"><span class="sr-only">Cari pengurus</span><i class="ph-bold ph-magnifying-glass" aria-hidden="true"></i><input id="keyword" type="search" name="keyword" value="{{ old('keyword', request('keyword')) }}" placeholder="Cari nama atau NIS..."></label><select class="form-select filter" name="filter_jabatan"><option value="">Semua jabatan</option><option value="ketua_kelas" {{ request('filter_jabatan') === 'ketua_kelas' ? 'selected' : '' }}>Ketua kelas</option><option value="wakil_kelas" {{ request('filter_jabatan') === 'wakil_kelas' ? 'selected' : '' }}>Wakil kelas</option><option value="sekretaris" {{ request('filter_jabatan') === 'sekretaris' ? 'selected' : '' }}>Sekretaris</option></select><select class="form-select filter" name="filter_kelas"><option value="">Semua kelas</option>@foreach ($kelas as $item)<option value="{{ $item->id_kelas }}" {{ request('filter_kelas') == $item->id_kelas ? 'selected' : '' }}>{{ $item->tingkatan.' '.$item->nama_jurusan.' '.$item->nama_kelas }}</option>@endforeach</select><button type="submit" class="btn btn-secondary">Terapkan</button></form>
        <div class="table-scroll" tabindex="0" aria-label="Tabel pengurus kelas"><table class="table table-bordered"><thead><tr><th scope="col">No</th><th scope="col">Profil</th><th scope="col">NIS</th><th scope="col">Nama lengkap</th><th scope="col">Jabatan</th><th scope="col">Kelas</th><th scope="col">Detail</th></tr></thead><tbody>@forelse ($pengurus as $item)<tr><td>{{ $loop->iteration }}</td><td>@include('layout.partials.entity-avatar', ['directory' => 'siswa', 'filename' => $item->foto_siswa, 'alt' => 'Foto '.$item->nama_siswa])</td><td>{{ $item->nis }}</td><td><strong class="table-primary-text">{{ $item->nama_siswa }}</strong></td><td><span class="role-label">{{ $item->jabatan.' '.$item->status_jabatan }}</span></td><td>{{ $item->tingkatan.' '.$item->nama_jurusan.' '.$item->nama_kelas }}</td><td class="table-actions"><a class="icon-action icon-action--info" href="{{ route('guru-piket.pengurus-kelas.detail', ['id' => $item->id_pengurus]) }}" aria-label="Lihat {{ $item->nama_siswa }}" title="Lihat pengurus"><i class="ph-bold ph-arrow-up-right" aria-hidden="true"></i></a></td></tr>@empty<tr><td colspan="7"><div class="table-empty-state"><i class="ph-bold ph-users-three" aria-hidden="true"></i><strong>Belum ada pengurus yang cocok</strong><span>Ubah filter untuk melihat pengurus kelas.</span></div></td></tr>@endforelse</tbody></table></div>{{ $pengurus->links() }}
    </section>
@endsection
