@extends('layout.layout')
@section('judul', 'Presensi sekolah')
@section('page-description', 'Periksa catatan kehadiran dan lakukan perubahan hanya saat diperlukan.')

@section('isi')
    <section class="workspace-page" aria-labelledby="piket-presensi-title">
        <header class="workspace-intro"><div><p class="eyebrow">Operasi piket</p><h2 id="piket-presensi-title">Kehadiran yang perlu dipantau.</h2><p>Filter per kelas, tanggal, atau status untuk menemukan catatan dengan cepat.</p></div><span class="workspace-index">02 / Piket</span></header>
        <form class="workspace-filters attendance-filters" action="" method="get" id="form"><label class="search-field" for="keyword"><span class="sr-only">Cari presensi</span><i class="ph-bold ph-magnifying-glass" aria-hidden="true"></i><input id="keyword" type="search" name="keyword" value="{{ old('keyword', request('keyword')) }}" placeholder="Cari nama siswa..."></label><select class="form-select filter" name="filter_kelas"><option value="">Semua kelas</option>@foreach ($kelas as $item)<option value="{{ $item->id_kelas }}" {{ request('filter_kelas') == $item->id_kelas ? 'selected' : '' }}>{{ $item->tingkatan.' '.$item->nama_jurusan.' '.$item->nama_kelas }}</option>@endforeach</select><select class="form-select" id="filter_bulan" name="filter_bulan"><option value="">Semua bulan</option>@foreach (['01'=>'Januari','02'=>'Februari','03'=>'Maret','04'=>'April','05'=>'Mei','06'=>'Juni','07'=>'Juli','08'=>'Agustus','09'=>'September','10'=>'Oktober','11'=>'November','12'=>'Desember'] as $value => $label)<option value="{{ $value }}" {{ request('filter_bulan') === $value ? 'selected' : '' }}>{{ $label }}</option>@endforeach</select><input type="date" class="form-control" id="filter_tanggal" value="{{ old('filter_tanggal', request('filter_tanggal')) }}" name="filter_tanggal" aria-label="Filter tanggal"><select class="form-select filter" name="filter_kehadiran"><option value="">Semua status</option><option value="hadir" {{ request('filter_kehadiran') === 'hadir' ? 'selected' : '' }}>Hadir</option><option value="izin" {{ request('filter_kehadiran') === 'izin' ? 'selected' : '' }}>Izin</option><option value="alpha" {{ request('filter_kehadiran') === 'alpha' ? 'selected' : '' }}>Alpha</option></select><button type="submit" class="btn btn-secondary">Terapkan</button><button type="button" class="btn btn-primary" id="downloadPDF"><i class="ph-bold ph-download-simple" aria-hidden="true"></i> Unduh PDF</button></form>
        <div class="table-scroll" tabindex="0" aria-label="Tabel presensi"><table class="table table-bordered"><thead><tr><th scope="col">No</th><th scope="col">NIS</th><th scope="col">Nama siswa</th><th scope="col">Tanggal</th><th scope="col">Kelas</th><th scope="col">Kehadiran</th><th scope="col">Bukti</th><th scope="col">Keterangan</th><th scope="col">Aksi</th></tr></thead><tbody>@forelse ($presensi as $item)<tr><td>{{ $loop->iteration }}</td><td>{{ $item->nis }}</td><td><strong class="table-primary-text">{{ $item->nama_siswa }}</strong></td><td>{{ $item->tanggal ? \Illuminate\Support\Carbon::parse($item->tanggal)->locale('id')->isoFormat('D MMM YYYY') : '-' }}</td><td>{{ $item->tingkatan.' '.$item->nama_jurusan.' '.$item->nama_kelas }}</td><td><span class="status-badge status-badge--{{ $item->status_kehadiran }}">{{ ucfirst($item->status_kehadiran) }}</span></td><td>@if ($item->foto_bukti && file_exists(public_path('presensi_bukti/'.$item->foto_bukti)))<img src="{{ asset('presensi_bukti/'.$item->foto_bukti) }}" alt="Bukti presensi {{ $item->nama_siswa }}">@else<span class="evidence-placeholder"><i class="ph-bold ph-image-square" aria-hidden="true"></i> Tidak ada</span>@endif</td><td>{{ $item->keterangan ?: '—' }}</td><td class="table-actions"><a class="icon-action icon-action--edit" href="{{ route('guru-piket.presensi.edit', ['id' => $item->id_presensi]) }}" aria-label="Edit presensi {{ $item->nama_siswa }}" title="Edit presensi"><i class="ph-bold ph-pencil-simple" aria-hidden="true"></i></a></td></tr>@empty<tr><td colspan="9"><div class="table-empty-state"><i class="ph-bold ph-calendar-check" aria-hidden="true"></i><strong>Belum ada presensi yang cocok</strong><span>Ubah filter untuk melihat catatan.</span></div></td></tr>@endforelse</tbody></table></div>{{ $presensi->links() }}
    </section>
@endsection
@section('footer')
    <script type="module">
        document.getElementById('downloadPDF')?.addEventListener('click', () => {
            const form = document.getElementById('form');
            if (!form) return;
            form.action = '{{ route('guru-piket.presensi.pdf') }}';
            form.submit();
        });
    </script>
@endsection
