@extends('layout.layout')
@section('judul', 'Kelola guru')
@section('page-description', 'Kelola akun guru, peran pendampingan, piket, dan wali kelas.')
@section('page-actions')
    <a href="{{ route('tata-usaha.guru.create') }}" class="btn btn-primary page-action"><i class="ph-bold ph-plus" aria-hidden="true"></i> Tambah guru</a>
@endsection

@section('isi')
    <section class="workspace-page" aria-labelledby="guru-workspace-title">
        <header class="workspace-intro"><div><p class="eyebrow">Akun sekolah</p><h2 id="guru-workspace-title">Orang yang menjaga operasi.</h2><p>Temukan guru berdasarkan nama atau peran yang sedang dijalankan.</p></div><span class="workspace-index">03 / Akun</span></header>
        <form action="" method="get" class="workspace-filters" id="form"><label class="search-field" for="keyword"><span class="sr-only">Cari guru</span><i class="ph-bold ph-magnifying-glass" aria-hidden="true"></i><input id="keyword" type="search" name="keyword" value="{{ old('keyword', request('keyword')) }}" placeholder="Cari nama guru..."></label><select class="form-select filter" name="filter_status"><option value="">Semua peran</option><option value="1" {{ request('filter_status') === '1' ? 'selected' : '' }}>Guru BK</option><option value="2" {{ request('filter_status') === '2' ? 'selected' : '' }}>Guru piket</option><option value="3" {{ request('filter_status') === '3' ? 'selected' : '' }}>Wali kelas</option></select><button type="submit" class="btn btn-secondary">Terapkan</button></form>
        <div class="table-scroll" tabindex="0" aria-label="Tabel guru"><table class="table table-bordered"><thead><tr><th scope="col">No</th><th scope="col">Profil</th><th scope="col">Nama guru</th><th scope="col">Peran</th><th scope="col">Aksi</th></tr></thead><tbody>
            @php $index = 1; @endphp
            @foreach (($guruBK ?? collect()) as $item)<tr><td>{{ $index++ }}</td><td>@include('layout.partials.entity-avatar', ['directory' => 'guru', 'filename' => $item->foto_guru, 'alt' => 'Foto '.$item->nama_guru])</td><td><strong class="table-primary-text">{{ $item->nama_guru }}</strong></td><td><span class="role-label">Guru BK</span></td><td class="table-actions"><a class="icon-action icon-action--info" href="{{ route('tata-usaha.guru.detail', ['id' => $item->id_guru]) }}" aria-label="Lihat {{ $item->nama_guru }}" title="Lihat guru"><i class="ph-bold ph-arrow-up-right" aria-hidden="true"></i></a><a class="icon-action icon-action--edit" href="{{ route('tata-usaha.guru.edit', ['id' => $item->id_guru]) }}" aria-label="Edit {{ $item->nama_guru }}" title="Edit guru"><i class="ph-bold ph-pencil-simple" aria-hidden="true"></i></a><button type="button" class="icon-action icon-action--danger" data-delete-url="{{ route('tata-usaha.guru.destroy') }}" data-delete-field="id_guru" data-delete-id="{{ $item->id_guru }}" aria-label="Hapus {{ $item->nama_guru }}" title="Hapus guru"><i class="ph-bold ph-trash" aria-hidden="true"></i></button></td></tr>@endforeach
            @foreach (($guruPiket ?? collect()) as $item)<tr><td>{{ $index++ }}</td><td>@include('layout.partials.entity-avatar', ['directory' => 'guru', 'filename' => $item->foto_guru, 'alt' => 'Foto '.$item->nama_guru])</td><td><strong class="table-primary-text">{{ $item->nama_guru }}</strong></td><td><span class="role-label">Guru piket</span></td><td class="table-actions"><a class="icon-action icon-action--info" href="{{ route('tata-usaha.guru.detail', ['id' => $item->id_guru]) }}" aria-label="Lihat {{ $item->nama_guru }}" title="Lihat guru"><i class="ph-bold ph-arrow-up-right" aria-hidden="true"></i></a><a class="icon-action icon-action--edit" href="{{ route('tata-usaha.guru.edit', ['id' => $item->id_guru]) }}" aria-label="Edit {{ $item->nama_guru }}" title="Edit guru"><i class="ph-bold ph-pencil-simple" aria-hidden="true"></i></a><button type="button" class="icon-action icon-action--danger" data-delete-url="{{ route('tata-usaha.guru.destroy') }}" data-delete-field="id_guru" data-delete-id="{{ $item->id_guru }}" aria-label="Hapus {{ $item->nama_guru }}" title="Hapus guru"><i class="ph-bold ph-trash" aria-hidden="true"></i></button></td></tr>@endforeach
            @foreach (($kelas ?? collect()) as $item)<tr><td>{{ $index++ }}</td><td>@include('layout.partials.entity-avatar', ['directory' => 'guru', 'filename' => $item->foto_guru, 'alt' => 'Foto '.$item->nama_guru])</td><td><strong class="table-primary-text">{{ $item->nama_guru }}</strong></td><td><span class="role-label">Wali kelas · {{ $item->tingkatan.' '.$item->nama_jurusan.' '.$item->nama_kelas }}</span></td><td class="table-actions"><a class="icon-action icon-action--info" href="{{ route('tata-usaha.guru.detail', ['id' => $item->id_guru]) }}" aria-label="Lihat {{ $item->nama_guru }}" title="Lihat guru"><i class="ph-bold ph-arrow-up-right" aria-hidden="true"></i></a><a class="icon-action icon-action--edit" href="{{ route('tata-usaha.guru.edit', ['id' => $item->id_guru]) }}" aria-label="Edit {{ $item->nama_guru }}" title="Edit guru"><i class="ph-bold ph-pencil-simple" aria-hidden="true"></i></a><button type="button" class="icon-action icon-action--danger" data-delete-url="{{ route('tata-usaha.guru.destroy') }}" data-delete-field="id_guru" data-delete-id="{{ $item->id_guru }}" aria-label="Hapus {{ $item->nama_guru }}" title="Hapus guru"><i class="ph-bold ph-trash" aria-hidden="true"></i></button></td></tr>@endforeach
            @if ($index === 1)<tr><td colspan="5"><div class="table-empty-state"><i class="ph-bold ph-users-three" aria-hidden="true"></i><strong>Belum ada guru yang cocok</strong><span>Ubah filter atau tambahkan akun guru.</span></div></td></tr>@endif
        </tbody></table></div>
    </section>
@endsection
