@extends('layout.layout')
@section('judul', 'Log aktivitas')
@section('page-description', 'Tinjau perubahan penting pada data sekolah dan pilih catatan yang perlu diarsipkan.')

@section('isi')
    <section class="workspace-page" aria-labelledby="logs-workspace-title">
        <header class="workspace-intro"><div><p class="eyebrow">Jejak perubahan</p><h2 id="logs-workspace-title">Apa yang berubah.</h2><p>Gunakan log untuk memahami siapa melakukan apa dan kapan.</p></div><span class="workspace-index">07 / Audit</span></header>
        <form action="" method="get" class="workspace-filters logs-filters" id="form"><label class="search-field" for="keyword"><span class="sr-only">Cari log</span><i class="ph-bold ph-magnifying-glass" aria-hidden="true"></i><input id="keyword" type="search" name="keyword" value="{{ old('keyword', request('keyword')) }}" placeholder="Cari aktor atau aktivitas..."></label><select class="form-select filter" name="filter_tabel"><option value="">Semua tabel</option>@foreach (['jurusan'=>'Jurusan','kelas'=>'Kelas','guru'=>'Guru','pengurus_kelas'=>'Pengurus kelas','siswa'=>'Siswa','presensi_siswa'=>'Presensi'] as $value => $label)<option value="{{ $value }}" {{ request('filter_tabel') === $value ? 'selected' : '' }}>{{ $label }}</option>@endforeach</select><select class="form-select filter" name="filter_aktor"><option value="">Semua aktor</option>@foreach (['Tata Usaha','Wali Kelas','Guru Piket','Guru BK','Pengurus Kelas','Siswa'] as $actor)<option value="{{ $actor }}" {{ request('filter_aktor') === $actor ? 'selected' : '' }}>{{ $actor }}</option>@endforeach</select><input type="date" class="form-control filter" name="filter_tanggal" value="{{ request('filter_tanggal') }}" aria-label="Filter tanggal"><select class="form-select filter" name="filter_aksi"><option value="">Semua aksi</option>@foreach (['Tambah','Edit','Hapus'] as $action)<option value="{{ $action }}" {{ request('filter_aksi') === $action ? 'selected' : '' }}>{{ $action }}</option>@endforeach</select><button type="submit" class="btn btn-secondary">Terapkan</button></form>
        <form action="{{ route('tata-usaha.logs.delete') }}" method="post" id="hapus"><div class="table-toolbar"><span><strong>{{ $logs->count() }}</strong> log ditampilkan</span><div><button type="button" class="btn btn-secondary" id="checkAll"><i class="ph-bold ph-check-square" aria-hidden="true"></i> Pilih semua</button><button type="button" class="btn btn-danger" id="submitFormButton"><i class="ph-bold ph-archive" aria-hidden="true"></i> Arsipkan</button></div></div>@csrf<div class="table-scroll" tabindex="0" aria-label="Tabel log aktivitas"><table class="table table-bordered"><thead><tr><th scope="col">No</th><th scope="col">Tabel</th><th scope="col">Aktor</th><th scope="col">Tanggal</th><th scope="col">Jam</th><th scope="col">Aksi</th><th scope="col">Record</th><th scope="col">Pilih</th></tr></thead><tbody>@forelse ($logs as $item)<tr><td>{{ $loop->iteration }}</td><td>{{ $item->tabel }}</td><td><strong class="table-primary-text">{{ $item->aktor }}</strong></td><td>{{ $item->tanggal }}</td><td class="mono-data">{{ $item->jam }}</td><td><span class="log-action log-action--{{ strtolower($item->aksi) }}">{{ $item->aksi }}</span></td><td>{{ $item->record }}</td><td><input class="checkbox" type="checkbox" name="id_logs[]" value="{{ $item->id_log }}" aria-label="Pilih log {{ $item->id_log }}"></td></tr>@empty<tr><td colspan="8"><div class="table-empty-state"><i class="ph-bold ph-notebook" aria-hidden="true"></i><strong>Belum ada aktivitas</strong><span>Log baru akan muncul setelah perubahan data.</span></div></td></tr>@endforelse</tbody></table></div></form>{{ $logs->links() }}
    </section>
@endsection
@section('footer')<script type="module">document.getElementById('checkAll')?.addEventListener('click', function() { document.querySelectorAll('.checkbox').forEach((checkbox) => checkbox.checked = true); }); document.getElementById('submitFormButton')?.addEventListener('click', async function() { const selected = document.querySelectorAll('.checkbox:checked'); if (!selected.length) { window.swal.fire({ title: 'Belum ada log dipilih', text: 'Pilih setidaknya satu catatan untuk diarsipkan.', icon: 'info', confirmButtonText: 'Mengerti' }); return; } const result = await window.swal.fire({ title: 'Arsipkan log terpilih?', text: 'Catatan tidak akan tampil di daftar aktif.', icon: 'warning', showCancelButton: true, confirmButtonText: 'Arsipkan', cancelButtonText: 'Batal', reverseButtons: true }); if (result.isConfirmed) document.getElementById('hapus').submit(); })</script>@endsection
