@extends('layout.layout')
@section('judul', 'Kelola siswa')
@section('page-description', 'Cari, perbarui, dan jaga data siswa aktif tetap siap digunakan.')
@section('page-actions')
    <a href="{{ route('tata-usaha.siswa.create') }}" class="btn btn-primary page-action"><i class="ph-bold ph-plus" aria-hidden="true"></i> Tambah siswa</a>
@endsection

@section('isi')
    <section class="workspace-page" aria-labelledby="siswa-workspace-title">
        <header class="workspace-intro"><div><p class="eyebrow">Akun siswa</p><h2 id="siswa-workspace-title">Data siswa yang siap dipakai.</h2><p>Gunakan filter untuk menemukan satu catatan tanpa kehilangan kelasnya.</p></div><span class="workspace-index">05 / Akun</span></header>
        <form action="" method="get" class="workspace-filters" id="form"><label class="search-field" for="keyword"><span class="sr-only">Cari siswa</span><i class="ph-bold ph-magnifying-glass" aria-hidden="true"></i><input id="keyword" type="search" name="keyword" value="{{ old('keyword', request('keyword')) }}" placeholder="Cari nama atau NIS..."></label><select class="form-select filter" name="filter_jenkel"><option value="">Semua gender</option><option value="laki-laki" {{ request('filter_jenkel') === 'laki-laki' ? 'selected' : '' }}>Laki-laki</option><option value="perempuan" {{ request('filter_jenkel') === 'perempuan' ? 'selected' : '' }}>Perempuan</option></select><select class="form-select filter" name="filter_kelas"><option value="">Semua kelas</option>@foreach ($kelas as $item)<option value="{{ $item->id_kelas }}" {{ request('filter_kelas') == $item->id_kelas ? 'selected' : '' }}>{{ $item->tingkatan.' '.$item->nama_jurusan.' '.$item->nama_kelas }}</option>@endforeach</select><select class="form-select filter" name="filter_status"><option value="">Semua status</option><option value="aktif" {{ request('filter_status') === 'aktif' ? 'selected' : '' }}>Aktif</option><option value="tidak_aktif" {{ request('filter_status') === 'tidak_aktif' ? 'selected' : '' }}>Tidak aktif</option></select><button type="submit" class="btn btn-secondary">Terapkan</button></form>
        <div class="table-scroll" tabindex="0" aria-label="Tabel siswa"><table class="table table-bordered"><thead><tr><th scope="col">No</th><th scope="col">Profil</th><th scope="col">NIS</th><th scope="col">Nama lengkap</th><th scope="col">Gender</th><th scope="col">Kelas</th><th scope="col">Status</th><th scope="col">Aksi</th></tr></thead><tbody>
            @forelse ($siswa as $item)<tr><td>{{ $loop->iteration }}</td><td>@include('layout.partials.entity-avatar', ['directory' => 'siswa', 'filename' => $item->foto_siswa, 'alt' => 'Foto '.$item->nama_siswa])</td><td>{{ $item->nis }}</td><td><strong class="table-primary-text">{{ $item->nama_siswa }}</strong></td><td>{{ $item->jenis_kelamin }}</td><td>{{ $item->tingkatan.' '.$item->nama_jurusan.' '.$item->nama_kelas }}</td><td><span class="status-badge status-badge--{{ $item->status_siswa === 'aktif' ? 'hadir' : 'alpha' }}">{{ str_replace('_', ' ', $item->status_siswa) }}</span></td><td class="table-actions"><a class="icon-action icon-action--info" href="{{ route('tata-usaha.siswa.detail', ['id' => $item->id_siswa]) }}" aria-label="Lihat {{ $item->nama_siswa }}" title="Lihat siswa"><i class="ph-bold ph-arrow-up-right" aria-hidden="true"></i></a><a class="icon-action icon-action--edit" href="{{ route('tata-usaha.siswa.edit', ['id' => $item->id_siswa]) }}" aria-label="Edit {{ $item->nama_siswa }}" title="Edit siswa"><i class="ph-bold ph-pencil-simple" aria-hidden="true"></i></a><button type="button" class="icon-action icon-action--danger" data-delete-url="{{ route('tata-usaha.siswa.destroy') }}" data-delete-field="id_siswa" data-delete-id="{{ $item->id_siswa }}" aria-label="Hapus {{ $item->nama_siswa }}" title="Hapus siswa"><i class="ph-bold ph-trash" aria-hidden="true"></i></button></td></tr>@empty<tr><td colspan="8"><div class="table-empty-state"><i class="ph-bold ph-users-three" aria-hidden="true"></i><strong>Belum ada siswa yang cocok</strong><span>Ubah filter atau tambahkan akun siswa.</span></div></td></tr>@endforelse
        </tbody></table></div>{{ $siswa->links() }}
    </section>
@endsection
